### ISSUE TITLE
Naamsverandering

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-citerra#18]
Citerra lijkt me geen gepaste naam voor de standaard zelf. Zegt weinig over wat het gaat en redelijk vluchtig qua concept.

Zou best zijn om de naam aan te passen naar iets in lijn met andere zaken binnen het domein van mobiliteit:

Mobiliteit: Toegangsrecht
Mobiliteit: autoluwe zones
etc.

**Comment by pheyvaer** [comment]
Dag @jitsedc, dat is waar. Dit is tijdens de laatste werkgroep besproken en de nieuwe naam zal zijn "Mobiliteit: Intelligente Toegang".

**Comment by pheyvaer** [comment]
Dit is gebeurd!
